name: Aggiornamento dati

on:
  schedule:
    - cron: "17 6 * * *"   # una volta al giorno circa
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 feedparser

      - name: Run fetch
        run: python scripts/fetch.py

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add public/data.json
          git commit -m "update data.json $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || echo "no changes"
          git push
